version: '2'

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
    expose:
      - 9090
    ports:
      - 9090:9090
    depends_on:
      - snmp-exporter
      - node-exporter

  snmp-exporter:
    image: amkay/snmp_exporter
    volumes:
      - ./snmp_exporter/:/etc/snmp_exporter/
    expose:
      - 9116

  node-exporter:
    image: prom/node-exporter
    expose:
      - 9100

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - ./grafana/config.env
