version: '2'

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    expose:
      - 9090
    ports:
      - 9090:9090
    depends_on:
      - snmp-exporter
      - node-exporter

  snmp-exporter:
    image: prom/snmp-exporter
    container_name: snmpexporter
    volumes:
      - ./snmp_exporter/:/etc/snmp_exporter/
    expose:
      - 9116
    ports:
      - 9116:9116

  node-exporter:
    image: prom/node-exporter
    container_name: nodeexporter
    expose:
      - 9100
    ports:
      - 9100:9100
      
  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - ./grafana/config.env
      
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    ports:
      - 9000:9000
    expose:
      - 9000