global:
  scrape_interval:     15s
  evaluation_interval: 15s
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'elsa'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'

    scrape_interval: 5s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
         - targets: ['192.168.1.252:9090','192.168.1.252:9100']

  - job_name: 'snmp'
    static_configs:
      - targets:
      # List of targets of the subnet
        - 192.168.1.1 # Mikrotik Router        
        - 192.168.1.3 # Cisco SW0
        - 192.168.1.4 # Cisco SW1
        
        #  Forti needs a special module snmp_forti
    metrics_path: /snmp
    params:
      module: [default]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'snmp-exporter:9116'  # SNMP exporter.
        
  - job_name: 'snmp_forti'
    static_configs:
      - targets:
        - 192.168.1.2 # fortigate device. 
    metrics_path: /snmp
    scrape_timeout : 15s
    params:
      module: [fortinet_fortigate]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.1.252:9116  # SNMP exporter IP, static ip recomended, docker bug: cant resolve snmp-exporter in job2!!