global:
  scrape_interval:     15s
  evaluation_interval: 15s
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'elsa'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'

    scrape_interval: 5s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
         - targets: ['localhost:9090','node-exporter:9100']

  - job_name: 'snmp'
    static_configs:
      - targets:
      # List of targets of the subnet
        - 192.168.0.1 # Router
       #  - 192.168.0.2 # Forti need special module
        - 192.168.0.3 # SW1
        - 192.168.0.4 # SW0
    metrics_path: /snmp
    params:
      module: [default]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'snmp-exporter:9116'  # SNMP exporter.
  - job_name: 'snmp_forti'
    static_configs:
      - targets:
        - 192.168.0.2 # fortigate device. 
    metrics_path: /snmp
    scrape_interval: 3m
    scrape_timeout : 3m
    params:
      module: [fortinet_fortigate]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp_exporter:9116  # SNMP exporter.   